# Generated by Django 5.0.4 on 2026-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_usuario_carrera_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
