# Generated by Django 5.0.4 on 2026-04-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0003_bloquehorario_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimnasio_abierto', models.BooleanField(default=True)),
                ('mensaje_cierre', models.CharField(default='El gimnasio se encuentra cerrado por receso universitario o mantención.', max_length=255)),
            ],
        ),
    ]
