# Generated by Django 5.0.4 on 2026-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0004_configuraciongimnasio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichafisica',
            name='fecha_evaluacion',
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='carrera_normalizada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='condicion_cardiaca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='dolor_pecho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='lesion_articular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='mareos_desmayos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='masa_muscular',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='medicacion_presion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='perimetro_cintura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='porcentaje_grasa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fichafisica',
            name='recomendacion_medica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichafisica',
            name='estatura_cm',
            field=models.IntegerField(default=170),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafisica',
            name='objetivo_principal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichafisica',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=170, max_digits=5),
            preserve_default=False,
        ),
    ]
